# Generated by Django 5.0.6 on 2024-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='aceptar_terminos',
            field=models.CharField(max_length=20),
        ),
    ]
